# Generated by Django 5.2 on 2025-04-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название:')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стоимость в Р.:')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
            ],
        ),
    ]
