# Generated by Django 5.2 on 2025-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в Р.:'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('favorite_recipes', models.ManyToManyField(blank=True, related_name='favorited_by', to='FoodBot.recipe', verbose_name='ID избранных рецептов:')),
            ],
        ),
    ]
