# Generated by Django 5.2 on 2025-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBot', '0002_alter_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Платная подписка:'),
        ),
    ]
