# Generated by Django 5.2 on 2025-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBot', '0004_create_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_recipes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_recipe_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
